inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - "**/*.rb"
    - "**/*.rake"
    - "."
  Exclude:
    - "vendor/**/*"
    - "db/schema.rb"
  NewCops: enable

Layout/LineLength:
  Max: 120
  Exclude:
    - "spec/**/*"

Style/BlockDelimiters:
  Exclude:
    - "spec/**/*"

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Layout/HeredocIndentation:
  Enabled: false

Metrics/ClassLength:
  Max: 175

Metrics/MethodLength:
  Max: 25

Metrics/ParameterLists:
  Max: 20

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false
